-- Project 06: Climate Risk Scoring (credit-efficient POC)

CREATE DATABASE IF NOT EXISTS CLIMATE_RISK COMMENT = 'Climate risk scoring - emissions, energy, risk tiers';
CREATE SCHEMA IF NOT EXISTS CLIMATE_RISK.STAGING;
CREATE SCHEMA IF NOT EXISTS CLIMATE_RISK.MODELS;
CREATE SCHEMA IF NOT EXISTS CLIMATE_RISK.RESULTS;

-- Staging: Country emissions (Climate Watch, top 50 emitters)
CREATE OR REPLACE VIEW CLIMATE_RISK.STAGING.COUNTRY_EMISSIONS AS
SELECT cw.GEO_ID, g.GEO_NAME AS COUNTRY_NAME, g.ISO_ALPHA2 AS COUNTRY_CODE,
    cw.VARIABLE, cw.VARIABLE_NAME, cw."DATE" AS OBSERVATION_DATE, cw.VALUE, cw.UNIT
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.CLIMATE_WATCH_TIMESERIES cw
LEFT JOIN SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.GEOGRAPHY_INDEX g ON cw.GEO_ID = g.GEO_ID
WHERE cw.GEO_ID LIKE 'country/%'
LIMIT 150000;

-- Staging: Risk feature matrix (pivoted GHG by sector, 5000 rows)
CREATE OR REPLACE VIEW CLIMATE_RISK.STAGING.RISK_FEATURE_MATRIX AS
WITH pivoted AS (
    SELECT cw.GEO_ID, g.GEO_NAME AS COUNTRY_NAME, cw."DATE" AS OBSERVATION_DATE,
        MAX(CASE WHEN cw.VARIABLE LIKE 'total_including_lulucf_all_ghg%' THEN cw.VALUE END) AS TOTAL_GHG,
        MAX(CASE WHEN cw.VARIABLE LIKE 'energy_all_ghg%' THEN cw.VALUE END) AS ENERGY_GHG,
        MAX(CASE WHEN cw.VARIABLE LIKE 'agriculture_all_ghg%' THEN cw.VALUE END) AS AGRICULTURE_GHG,
        MAX(CASE WHEN cw.VARIABLE LIKE 'waste_all_ghg%' THEN cw.VALUE END) AS WASTE_GHG,
        MAX(CASE WHEN cw.VARIABLE LIKE 'industrial_processes_all_ghg%' THEN cw.VALUE END) AS INDUSTRIAL_GHG,
        MAX(CASE WHEN cw.VARIABLE LIKE 'transportation_all_ghg%' THEN cw.VALUE END) AS TRANSPORT_GHG
    FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.CLIMATE_WATCH_TIMESERIES cw
    LEFT JOIN SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.GEOGRAPHY_INDEX g ON cw.GEO_ID = g.GEO_ID
    WHERE cw.GEO_ID LIKE 'country/%'
    GROUP BY cw.GEO_ID, g.GEO_NAME, cw."DATE" HAVING TOTAL_GHG IS NOT NULL
)
SELECT *, COALESCE(ENERGY_GHG,0)/NULLIF(TOTAL_GHG,0) AS ENERGY_SHARE,
    COALESCE(AGRICULTURE_GHG,0)/NULLIF(TOTAL_GHG,0) AS AGRICULTURE_SHARE,
    CASE NTILE(3) OVER (ORDER BY TOTAL_GHG DESC)
        WHEN 1 THEN 'High Risk' WHEN 2 THEN 'Medium Risk' ELSE 'Low Risk'
    END AS RISK_TIER
FROM pivoted LIMIT 5000;

-- Classifier training view (numeric features only)
CREATE OR REPLACE VIEW CLIMATE_RISK.STAGING.CLASSIFIER_TRAINING AS
SELECT TOTAL_GHG, COALESCE(ENERGY_GHG,0) AS ENERGY_GHG,
    COALESCE(AGRICULTURE_GHG,0) AS AGRICULTURE_GHG,
    COALESCE(WASTE_GHG,0) AS WASTE_GHG,
    COALESCE(INDUSTRIAL_GHG,0) AS INDUSTRIAL_GHG,
    COALESCE(TRANSPORT_GHG,0) AS TRANSPORT_GHG,
    ENERGY_SHARE, AGRICULTURE_SHARE, RISK_TIER
FROM CLIMATE_RISK.STAGING.RISK_FEATURE_MATRIX;

-- Train classifier
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION CLIMATE_RISK.MODELS.RISK_TIER_CLASSIFIER(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'CLIMATE_RISK.STAGING.CLASSIFIER_TRAINING'),
    TARGET_COLNAME => 'RISK_TIER'
);

-- Feature store with predictions
CREATE OR REPLACE TABLE CLIMATE_RISK.RESULTS.FEATURE_STORE_CLIMATE AS
SELECT GEO_ID, COUNTRY_NAME, OBSERVATION_DATE, TOTAL_GHG, ENERGY_GHG,
    AGRICULTURE_GHG, WASTE_GHG, INDUSTRIAL_GHG, TRANSPORT_GHG,
    ENERGY_SHARE, AGRICULTURE_SHARE, RISK_TIER,
    CLIMATE_RISK.MODELS.RISK_TIER_CLASSIFIER!PREDICT(
        INPUT_DATA => OBJECT_CONSTRUCT('TOTAL_GHG',TOTAL_GHG,'ENERGY_GHG',COALESCE(ENERGY_GHG,0),
            'AGRICULTURE_GHG',COALESCE(AGRICULTURE_GHG,0),'WASTE_GHG',COALESCE(WASTE_GHG,0),
            'INDUSTRIAL_GHG',COALESCE(INDUSTRIAL_GHG,0),'TRANSPORT_GHG',COALESCE(TRANSPORT_GHG,0),
            'ENERGY_SHARE',ENERGY_SHARE,'AGRICULTURE_SHARE',AGRICULTURE_SHARE)
    ):class::VARCHAR AS PREDICTED_TIER
FROM CLIMATE_RISK.STAGING.RISK_FEATURE_MATRIX;

-- Emissions trends
CREATE OR REPLACE TABLE CLIMATE_RISK.RESULTS.EMISSIONS_TRENDS AS
WITH total_ghg AS (
    SELECT GEO_ID, COUNTRY_NAME, OBSERVATION_DATE, VALUE
    FROM CLIMATE_RISK.STAGING.COUNTRY_EMISSIONS WHERE VARIABLE LIKE 'total_including_lulucf_all_ghg%'
)
SELECT *, LAG(VALUE) OVER (PARTITION BY GEO_ID ORDER BY OBSERVATION_DATE) AS PREV_VALUE,
    ROUND((VALUE - LAG(VALUE) OVER (PARTITION BY GEO_ID ORDER BY OBSERVATION_DATE))
        / NULLIF(LAG(VALUE) OVER (PARTITION BY GEO_ID ORDER BY OBSERVATION_DATE), 0) * 100, 2) AS YOY_CHANGE_PCT
FROM total_ghg;
