-- Project 04: Stock Price Forecasting
-- Step 01: Staging — Pivot OHLCV + Feature Engineering

-- Pivot marketplace narrow format into wide OHLCV (10 major tickers)
CREATE OR REPLACE VIEW ML_STOCKS.STAGING.DAILY_OHLCV AS
SELECT
    TICKER, "DATE",
    MAX(CASE WHEN VARIABLE = 'all-day_high' THEN VALUE END) AS HIGH_PRICE,
    MAX(CASE WHEN VARIABLE = 'all-day_low' THEN VALUE END) AS LOW_PRICE,
    MAX(CASE WHEN VARIABLE = 'post-market_close' THEN VALUE END) AS CLOSE_PRICE,
    MAX(CASE WHEN VARIABLE = 'pre-market_open' THEN VALUE END) AS OPEN_PRICE,
    MAX(CASE WHEN VARIABLE = 'nasdaq_volume' THEN VALUE END) AS VOLUME
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.STOCK_PRICE_TIMESERIES
WHERE TICKER IN ('AAPL','MSFT','GOOGL','AMZN','NVDA','META','TSLA','JPM','V','JNJ')
  AND VARIABLE IN ('all-day_high','all-day_low','post-market_close','pre-market_open','nasdaq_volume')
GROUP BY TICKER, "DATE"
HAVING CLOSE_PRICE IS NOT NULL;

-- Feature engineering: technical indicators via window functions
CREATE OR REPLACE VIEW ML_STOCKS.STAGING.FEATURE_ENGINEERED AS
WITH step1 AS (
    SELECT TICKER, "DATE", CLOSE_PRICE, HIGH_PRICE, LOW_PRICE, OPEN_PRICE, VOLUME,
        LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY "DATE") AS PREV_CLOSE
    FROM ML_STOCKS.STAGING.DAILY_OHLCV
),
step2 AS (
    SELECT *,
        LN(CLOSE_PRICE / NULLIF(PREV_CLOSE, 0)) AS LOG_RETURN_1D,
        GREATEST(CLOSE_PRICE - PREV_CLOSE, 0) AS GAIN,
        GREATEST(PREV_CLOSE - CLOSE_PRICE, 0) AS LOSS,
        (CLOSE_PRICE - OPEN_PRICE) / NULLIF(OPEN_PRICE, 0) AS DAILY_RETURN
    FROM step1 WHERE PREV_CLOSE IS NOT NULL
),
step3 AS (
    SELECT *,
        AVG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY "DATE" ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS SMA_7,
        AVG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY "DATE" ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS SMA_20,
        AVG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY "DATE" ROWS BETWEEN 49 PRECEDING AND CURRENT ROW) AS SMA_50,
        STDDEV(LOG_RETURN_1D) OVER (PARTITION BY TICKER ORDER BY "DATE" ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS VOLATILITY_20D,
        AVG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY "DATE" ROWS BETWEEN 19 PRECEDING AND CURRENT ROW)
            + 2 * STDDEV(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY "DATE" ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS BOLLINGER_UPPER,
        AVG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY "DATE" ROWS BETWEEN 19 PRECEDING AND CURRENT ROW)
            - 2 * STDDEV(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY "DATE" ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS BOLLINGER_LOWER,
        AVG(GAIN) OVER (PARTITION BY TICKER ORDER BY "DATE" ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS AVG_GAIN_14,
        AVG(LOSS) OVER (PARTITION BY TICKER ORDER BY "DATE" ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS AVG_LOSS_14,
        AVG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY "DATE" ROWS BETWEEN 11 PRECEDING AND CURRENT ROW)
            - AVG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY "DATE" ROWS BETWEEN 25 PRECEDING AND CURRENT ROW) AS MACD_APPROX
    FROM step2
)
SELECT TICKER, "DATE", CLOSE_PRICE, HIGH_PRICE, LOW_PRICE, OPEN_PRICE, VOLUME,
    LOG_RETURN_1D, DAILY_RETURN, SMA_7, SMA_20, SMA_50, VOLATILITY_20D,
    BOLLINGER_UPPER, BOLLINGER_LOWER,
    CASE WHEN AVG_LOSS_14 = 0 THEN 100
         ELSE 100 - (100 / (1 + AVG_GAIN_14 / NULLIF(AVG_LOSS_14, 0)))
    END AS RSI_14,
    MACD_APPROX
FROM step3 WHERE "DATE" >= '2019-01-01';

-- Forecast input (simple: ticker + date + close)
CREATE OR REPLACE VIEW ML_STOCKS.STAGING.FORECAST_INPUT AS
SELECT TICKER, "DATE", CLOSE_PRICE
FROM ML_STOCKS.STAGING.DAILY_OHLCV WHERE "DATE" >= '2020-01-01';

-- Anomaly detection: train on 2019-2025, test on 2025+
CREATE OR REPLACE VIEW ML_STOCKS.STAGING.ANOMALY_TRAIN AS
SELECT TICKER, "DATE", DAILY_RETURN
FROM ML_STOCKS.STAGING.FEATURE_ENGINEERED
WHERE DAILY_RETURN IS NOT NULL AND "DATE" < '2025-06-01';

CREATE OR REPLACE VIEW ML_STOCKS.STAGING.ANOMALY_TEST AS
SELECT TICKER, "DATE", DAILY_RETURN
FROM ML_STOCKS.STAGING.FEATURE_ENGINEERED
WHERE DAILY_RETURN IS NOT NULL AND "DATE" >= '2025-06-01';
