-- Project 03: Economic Data Vault 2.0
-- Step 01: Staging Views (hash keys + row caps for POC)

-- Federal Reserve (financial accounts, money supply)
CREATE OR REPLACE VIEW ECON_VAULT.STAGING.STG_FEDERAL_RESERVE AS
SELECT
    MD5(VARIABLE) AS INDICATOR_HK,
    MD5(GEO_ID) AS GEOGRAPHY_HK,
    MD5(VARIABLE || '|' || GEO_ID) AS LINK_HK,
    GEO_ID, VARIABLE, VARIABLE_NAME,
    "DATE" AS OBSERVATION_DATE, VALUE, UNIT,
    'FEDERAL_RESERVE' AS RECORD_SOURCE,
    CURRENT_TIMESTAMP() AS LOAD_DTS
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FEDERAL_RESERVE_TIMESERIES
WHERE VARIABLE IN (
    SELECT VARIABLE FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FEDERAL_RESERVE_ATTRIBUTES
    WHERE CATEGORY IN ('Total assets','Total financial assets','Treasury securities; asset',
                       'Corporate equities; asset','Money market fund shares; asset')
)
LIMIT 2000000;

-- BLS Employment (US national only)
CREATE OR REPLACE VIEW ECON_VAULT.STAGING.STG_BLS_EMPLOYMENT AS
SELECT
    MD5(VARIABLE) AS INDICATOR_HK,
    MD5(GEO_ID) AS GEOGRAPHY_HK,
    MD5(VARIABLE || '|' || GEO_ID) AS LINK_HK,
    GEO_ID, VARIABLE, VARIABLE_NAME,
    "DATE" AS OBSERVATION_DATE, VALUE, 'Persons' AS UNIT,
    'BLS_EMPLOYMENT' AS RECORD_SOURCE,
    CURRENT_TIMESTAMP() AS LOAD_DTS
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.BUREAU_OF_LABOR_STATISTICS_EMPLOYMENT_TIMESERIES
WHERE GEO_ID = 'country/USA'
LIMIT 1500000;

-- US Treasury (all - small table)
CREATE OR REPLACE VIEW ECON_VAULT.STAGING.STG_US_TREASURY AS
SELECT
    MD5(VARIABLE) AS INDICATOR_HK,
    MD5(GEO_ID) AS GEOGRAPHY_HK,
    MD5(VARIABLE || '|' || GEO_ID) AS LINK_HK,
    GEO_ID, VARIABLE, VARIABLE_NAME,
    "DATE" AS OBSERVATION_DATE, VALUE, UNIT,
    'US_TREASURY' AS RECORD_SOURCE,
    CURRENT_TIMESTAMP() AS LOAD_DTS
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.US_TREASURY_TIMESERIES;

-- World Bank (top 50 countries by GDP)
CREATE OR REPLACE VIEW ECON_VAULT.STAGING.STG_WORLD_BANK AS
SELECT
    MD5(VARIABLE) AS INDICATOR_HK,
    MD5(GEO_ID) AS GEOGRAPHY_HK,
    MD5(VARIABLE || '|' || GEO_ID) AS LINK_HK,
    GEO_ID, VARIABLE, VARIABLE_NAME,
    "DATE" AS OBSERVATION_DATE, VALUE, UNIT,
    'WORLD_BANK' AS RECORD_SOURCE,
    CURRENT_TIMESTAMP() AS LOAD_DTS
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.WORLD_BANK_TIMESERIES
WHERE GEO_ID IN (
    'country/USA','country/CHN','country/JPN','country/DEU','country/GBR',
    'country/FRA','country/IND','country/ITA','country/BRA','country/CAN',
    'country/KOR','country/AUS','country/ESP','country/MEX','country/IDN',
    'country/NLD','country/SAU','country/TUR','country/CHE','country/POL',
    'country/SWE','country/BEL','country/THA','country/NGA','country/AUT',
    'country/NOR','country/ARE','country/ISR','country/ZAF','country/IRL',
    'country/DNK','country/SGP','country/HKG','country/MYS','country/PHL',
    'country/COL','country/EGY','country/CHL','country/FIN','country/PAK',
    'country/CZE','country/PER','country/PRT','country/NZL','country/ROU',
    'country/GRC','country/IRQ','country/QAT','country/DZA','country/KAZ'
)
LIMIT 1000000;

-- Vintage (BEA revision tracking - demonstrates key DV2 pattern)
CREATE OR REPLACE VIEW ECON_VAULT.STAGING.STG_VINTAGE AS
SELECT
    MD5(VARIABLE) AS INDICATOR_HK,
    MD5(GEO_ID) AS GEOGRAPHY_HK,
    MD5(VARIABLE || '|' || GEO_ID) AS LINK_HK,
    GEO_ID, VARIABLE, VARIABLE_NAME,
    "DATE" AS OBSERVATION_DATE, VALUE, UNIT,
    RELEASE_DATE, SOURCE AS SOURCE_URL,
    'VINTAGE_BEA' AS RECORD_SOURCE,
    CURRENT_TIMESTAMP() AS LOAD_DTS
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FINANCIAL_ECONOMIC_INDICATORS_TIMESERIES_VINTAGE;
