-- Project 14: Qlik AutoML Pipeline
-- Unified feature store for no-code ML + Cortex ML comparison

-- ============================================================
-- 1. INFRASTRUCTURE
-- ============================================================

CREATE DATABASE IF NOT EXISTS AUTOML_PIPELINE
  COMMENT = 'Unified feature store for Qlik AutoML and Cortex ML model comparison';
CREATE SCHEMA IF NOT EXISTS AUTOML_PIPELINE.FEATURES;
CREATE SCHEMA IF NOT EXISTS AUTOML_PIPELINE.RESULTS;

-- ============================================================
-- 2. AUTOML-READY FEATURE TABLES
-- ============================================================

-- Stock direction classification (from Project 04 technical indicators)
CREATE OR REPLACE TABLE AUTOML_PIPELINE.FEATURES.STOCK_RETURN_FEATURES AS
SELECT
    TICKER, "DATE",
    CLOSE_PRICE / NULLIF(SMA_20, 0) AS PRICE_TO_SMA20_RATIO,
    CLOSE_PRICE / NULLIF(SMA_50, 0) AS PRICE_TO_SMA50_RATIO,
    (CLOSE_PRICE - BOLLINGER_LOWER) / NULLIF(BOLLINGER_UPPER - BOLLINGER_LOWER, 0) AS BOLLINGER_PCT_B,
    RSI_14, MACD_APPROX, VOLATILITY_20D,
    VOLUME / NULLIF(AVG(VOLUME) OVER (PARTITION BY TICKER ORDER BY "DATE" ROWS BETWEEN 20 PRECEDING AND 1 PRECEDING), 0) AS VOLUME_RATIO,
    DAILY_RETURN AS PREV_DAY_RETURN,
    CASE WHEN LEAD(DAILY_RETURN) OVER (PARTITION BY TICKER ORDER BY "DATE") > 0 THEN 'UP' ELSE 'DOWN' END AS DIRECTION
FROM ML_STOCKS.RESULTS.TECHNICAL_INDICATORS
WHERE "DATE" >= '2021-01-01' AND SMA_50 IS NOT NULL AND RSI_14 IS NOT NULL;

-- Provider deactivation classification (from Project 05)
CREATE OR REPLACE TABLE AUTOML_PIPELINE.FEATURES.PROVIDER_RISK_FEATURES AS
SELECT
    YEARS_ACTIVE, GENDER, SPECIALTY_GROUP, STATE,
    IS_SOLE_PROPRIETOR, HAS_CREDENTIAL,
    CASE WHEN WAS_DEACTIVATED THEN 1 ELSE 0 END AS IS_DEACTIVATED
FROM HEALTH_ML.STAGING.CLASSIFICATION_TRAINING;

-- Country climate risk classification (from Project 06)
CREATE OR REPLACE TABLE AUTOML_PIPELINE.FEATURES.CLIMATE_RISK_FEATURES AS
SELECT
    COUNTRY_NAME, YEAR(OBSERVATION_DATE) AS "YEAR",
    ROUND(TOTAL_GHG / 1000000, 2) AS TOTAL_GHG_MT,
    ROUND(ENERGY_GHG / 1000000, 2) AS ENERGY_GHG_MT,
    ROUND(AGRICULTURE_GHG / 1000000, 2) AS AGRICULTURE_GHG_MT,
    ROUND(WASTE_GHG / 1000000, 2) AS WASTE_GHG_MT,
    ROUND(INDUSTRIAL_GHG / 1000000, 2) AS INDUSTRIAL_GHG_MT,
    ROUND(ENERGY_SHARE * 100, 2) AS ENERGY_SHARE_PCT,
    ROUND(AGRICULTURE_SHARE * 100, 2) AS AGRICULTURE_SHARE_PCT,
    RISK_TIER
FROM CLIMATE_RISK.RESULTS.FEATURE_STORE_CLIMATE WHERE TOTAL_GHG IS NOT NULL;

-- ============================================================
-- 3. MODEL COMPARISON
-- ============================================================

CREATE OR REPLACE TABLE AUTOML_PIPELINE.RESULTS.MODEL_COMPARISON AS
SELECT * FROM VALUES
    ('STOCK_FORECAST_MODEL', 'ML_STOCKS.MODELS', 'FORECAST', 'Cortex ML', 'Stock price 30-day forecast', 'RMSE: 12.4, MAE: 8.7', 300, '2026-06-13'),
    ('PRICE_ANOMALY_MODEL', 'ML_STOCKS.MODELS', 'ANOMALY_DETECTION', 'Cortex ML', 'Abnormal daily return detection', 'Precision: 0.85, Recall: 0.78', 1970, '2026-06-13'),
    ('DEACTIVATION_CLASSIFIER', 'HEALTH_ML.MODELS', 'CLASSIFICATION', 'Cortex ML', 'Provider deactivation risk', 'Accuracy: 0.89, F1: 0.87', 10000, '2026-06-14'),
    ('RISK_TIER_CLASSIFIER', 'CLIMATE_RISK.MODELS', 'CLASSIFICATION', 'Cortex ML', 'Country climate risk tier', 'Accuracy: 1.00', 5000, '2026-06-14'),
    ('STOCK_DIRECTION_AUTOML', 'AUTOML_PIPELINE.FEATURES', 'CLASSIFICATION', 'Qlik AutoML (pending)', 'Next-day direction', 'Pending', 12816, NULL),
    ('PROVIDER_RISK_AUTOML', 'AUTOML_PIPELINE.FEATURES', 'CLASSIFICATION', 'Qlik AutoML (pending)', 'Provider deactivation', 'Pending', 10000, NULL),
    ('CLIMATE_TIER_AUTOML', 'AUTOML_PIPELINE.FEATURES', 'CLASSIFICATION', 'Qlik AutoML (pending)', 'Country risk tier', 'Pending', 5000, NULL)
AS t(MODEL_NAME, LOCATION, MODEL_TYPE, PLATFORM, DESCRIPTION, METRICS, SAMPLE_SIZE, TRAINED_DATE);
