-- Project 04: Stock Price Forecasting
-- Step 02: Cortex ML Models (FORECAST + ANOMALY_DETECTION)

-- ===== FORECAST MODEL =====
-- Multi-series time-series forecasting on daily close prices
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML_STOCKS.MODELS.STOCK_FORECAST_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ML_STOCKS.STAGING.FORECAST_INPUT'),
    TIMESTAMP_COLNAME => 'DATE',
    TARGET_COLNAME => 'CLOSE_PRICE',
    SERIES_COLNAME => 'TICKER'
);

-- Generate 30-day predictions with 95% confidence interval
CALL ML_STOCKS.MODELS.STOCK_FORECAST_MODEL!FORECAST(
    FORECASTING_PERIODS => 30,
    CONFIG_OBJECT => {'prediction_interval': 0.95}
);

-- Store forecast results
CREATE OR REPLACE TABLE ML_STOCKS.RESULTS.FORECAST_PREDICTIONS AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- ===== ANOMALY DETECTION MODEL =====
-- Trained on historical returns (2019-2025), detects outliers in recent data
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML_STOCKS.MODELS.PRICE_ANOMALY_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ML_STOCKS.STAGING.ANOMALY_TRAIN'),
    SERIES_COLNAME => 'TICKER',
    TIMESTAMP_COLNAME => 'DATE',
    TARGET_COLNAME => 'DAILY_RETURN',
    LABEL_COLNAME => ''
);

-- Detect anomalies on 2025+ test data (99% confidence)
CALL ML_STOCKS.MODELS.PRICE_ANOMALY_MODEL!DETECT_ANOMALIES(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ML_STOCKS.STAGING.ANOMALY_TEST'),
    TIMESTAMP_COLNAME => 'DATE',
    TARGET_COLNAME => 'DAILY_RETURN',
    SERIES_COLNAME => 'TICKER',
    CONFIG_OBJECT => {'prediction_interval': 0.99}
);

-- Store anomaly results
CREATE OR REPLACE TABLE ML_STOCKS.RESULTS.DETECTED_ANOMALIES AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- ===== TECHNICAL INDICATORS (materialized for Qlik) =====
CREATE OR REPLACE TABLE ML_STOCKS.RESULTS.TECHNICAL_INDICATORS AS
SELECT TICKER, "DATE", CLOSE_PRICE, HIGH_PRICE, LOW_PRICE, OPEN_PRICE, VOLUME,
    SMA_7, SMA_20, SMA_50, VOLATILITY_20D,
    BOLLINGER_UPPER, BOLLINGER_LOWER, RSI_14, MACD_APPROX, DAILY_RETURN
FROM ML_STOCKS.STAGING.FEATURE_ENGINEERED;
