-- Project 03: Economic Data Vault 2.0
-- Step 02: Raw Vault (Hubs, Links, Satellites)

-- ===== HUBS (Business Keys) =====

CREATE OR REPLACE DYNAMIC TABLE ECON_VAULT.RAW_VAULT.HUB_INDICATOR
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT DISTINCT INDICATOR_HK, VARIABLE,
    MIN(LOAD_DTS) AS LOAD_DTS, MIN(RECORD_SOURCE) AS RECORD_SOURCE
FROM (
    SELECT INDICATOR_HK, VARIABLE, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_FEDERAL_RESERVE
    UNION ALL SELECT INDICATOR_HK, VARIABLE, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_BLS_EMPLOYMENT
    UNION ALL SELECT INDICATOR_HK, VARIABLE, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_US_TREASURY
    UNION ALL SELECT INDICATOR_HK, VARIABLE, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_WORLD_BANK
    UNION ALL SELECT INDICATOR_HK, VARIABLE, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_VINTAGE
) GROUP BY INDICATOR_HK, VARIABLE;

CREATE OR REPLACE DYNAMIC TABLE ECON_VAULT.RAW_VAULT.HUB_GEOGRAPHY
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT DISTINCT GEOGRAPHY_HK, GEO_ID,
    MIN(LOAD_DTS) AS LOAD_DTS, MIN(RECORD_SOURCE) AS RECORD_SOURCE
FROM (
    SELECT GEOGRAPHY_HK, GEO_ID, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_FEDERAL_RESERVE
    UNION ALL SELECT GEOGRAPHY_HK, GEO_ID, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_BLS_EMPLOYMENT
    UNION ALL SELECT GEOGRAPHY_HK, GEO_ID, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_US_TREASURY
    UNION ALL SELECT GEOGRAPHY_HK, GEO_ID, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_WORLD_BANK
    UNION ALL SELECT GEOGRAPHY_HK, GEO_ID, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_VINTAGE
) GROUP BY GEOGRAPHY_HK, GEO_ID;

-- ===== LINKS (Relationships) =====

CREATE OR REPLACE DYNAMIC TABLE ECON_VAULT.RAW_VAULT.LINK_INDICATOR_GEOGRAPHY
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT DISTINCT LINK_HK, INDICATOR_HK, GEOGRAPHY_HK,
    MIN(LOAD_DTS) AS LOAD_DTS, MIN(RECORD_SOURCE) AS RECORD_SOURCE
FROM (
    SELECT LINK_HK, INDICATOR_HK, GEOGRAPHY_HK, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_FEDERAL_RESERVE
    UNION ALL SELECT LINK_HK, INDICATOR_HK, GEOGRAPHY_HK, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_BLS_EMPLOYMENT
    UNION ALL SELECT LINK_HK, INDICATOR_HK, GEOGRAPHY_HK, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_US_TREASURY
    UNION ALL SELECT LINK_HK, INDICATOR_HK, GEOGRAPHY_HK, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_WORLD_BANK
    UNION ALL SELECT LINK_HK, INDICATOR_HK, GEOGRAPHY_HK, LOAD_DTS, RECORD_SOURCE FROM ECON_VAULT.STAGING.STG_VINTAGE
) GROUP BY LINK_HK, INDICATOR_HK, GEOGRAPHY_HK;

-- ===== SATELLITES (Context + History) =====

CREATE OR REPLACE DYNAMIC TABLE ECON_VAULT.RAW_VAULT.SAT_INDICATOR_DETAILS
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT DISTINCT INDICATOR_HK, VARIABLE_NAME, UNIT, RECORD_SOURCE,
    MD5(VARIABLE_NAME || '|' || COALESCE(UNIT,'') || '|' || RECORD_SOURCE) AS HASH_DIFF,
    MIN(LOAD_DTS) AS LOAD_DTS
FROM (
    SELECT INDICATOR_HK, VARIABLE_NAME, UNIT, RECORD_SOURCE, LOAD_DTS FROM ECON_VAULT.STAGING.STG_FEDERAL_RESERVE
    UNION ALL SELECT INDICATOR_HK, VARIABLE_NAME, UNIT, RECORD_SOURCE, LOAD_DTS FROM ECON_VAULT.STAGING.STG_BLS_EMPLOYMENT
    UNION ALL SELECT INDICATOR_HK, VARIABLE_NAME, UNIT, RECORD_SOURCE, LOAD_DTS FROM ECON_VAULT.STAGING.STG_US_TREASURY
    UNION ALL SELECT INDICATOR_HK, VARIABLE_NAME, UNIT, RECORD_SOURCE, LOAD_DTS FROM ECON_VAULT.STAGING.STG_WORLD_BANK
    UNION ALL SELECT INDICATOR_HK, VARIABLE_NAME, UNIT, RECORD_SOURCE, LOAD_DTS FROM ECON_VAULT.STAGING.STG_VINTAGE
) GROUP BY INDICATOR_HK, VARIABLE_NAME, UNIT, RECORD_SOURCE, HASH_DIFF;

-- Observation satellite (the time-series values)
CREATE OR REPLACE DYNAMIC TABLE ECON_VAULT.RAW_VAULT.SAT_OBSERVATION
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT LINK_HK, OBSERVATION_DATE, VALUE, RECORD_SOURCE,
    MD5(CAST(VALUE AS VARCHAR) || '|' || CAST(OBSERVATION_DATE AS VARCHAR)) AS HASH_DIFF,
    LOAD_DTS
FROM (
    SELECT LINK_HK, OBSERVATION_DATE, VALUE, RECORD_SOURCE, LOAD_DTS FROM ECON_VAULT.STAGING.STG_FEDERAL_RESERVE
    UNION ALL SELECT LINK_HK, OBSERVATION_DATE, VALUE, RECORD_SOURCE, LOAD_DTS FROM ECON_VAULT.STAGING.STG_BLS_EMPLOYMENT
    UNION ALL SELECT LINK_HK, OBSERVATION_DATE, VALUE, RECORD_SOURCE, LOAD_DTS FROM ECON_VAULT.STAGING.STG_US_TREASURY
    UNION ALL SELECT LINK_HK, OBSERVATION_DATE, VALUE, RECORD_SOURCE, LOAD_DTS FROM ECON_VAULT.STAGING.STG_WORLD_BANK
);

-- Vintage satellite (revision tracking - key DV2 differentiator)
CREATE OR REPLACE DYNAMIC TABLE ECON_VAULT.RAW_VAULT.SAT_OBSERVATION_VINTAGE
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT LINK_HK, OBSERVATION_DATE, RELEASE_DATE, VALUE, SOURCE_URL, RECORD_SOURCE,
    MD5(CAST(VALUE AS VARCHAR) || '|' || CAST(RELEASE_DATE AS VARCHAR)) AS HASH_DIFF,
    LOAD_DTS
FROM ECON_VAULT.STAGING.STG_VINTAGE;
