-- =============================================================
-- Project 02: Real-Time Weather Pipeline
-- Step 02: CURATED Layer (Dynamic Tables)
-- =============================================================

-- Latest reading per station (pivoted to wide row)
-- Target lag: 15 minutes for near-real-time monitoring
CREATE OR REPLACE DYNAMIC TABLE WEATHER_DOMAIN.CURATED.LATEST_STATION_READINGS
  TARGET_LAG = '15 minutes'
  WAREHOUSE = WEATHER_WH
AS
WITH ranked AS (
    SELECT
        NWS_WEATHER_STATION_ID,
        VARIABLE,
        VALUE,
        TIMESTAMP,
        ROW_NUMBER() OVER (
            PARTITION BY NWS_WEATHER_STATION_ID, VARIABLE
            ORDER BY TIMESTAMP DESC
        ) AS rn
    FROM WEATHER_DOMAIN.RAW.WEATHER_OBSERVATIONS
)
SELECT
    NWS_WEATHER_STATION_ID,
    MAX(TIMESTAMP) AS LAST_OBSERVATION_TIME,
    MAX(CASE WHEN VARIABLE = 'temperature' THEN VALUE END) AS TEMPERATURE_C,
    MAX(CASE WHEN VARIABLE = 'dew_point' THEN VALUE END) AS DEW_POINT_C,
    MAX(CASE WHEN VARIABLE = 'relative_humidity' THEN VALUE END) AS HUMIDITY_PCT,
    MAX(CASE WHEN VARIABLE = 'wind_speed' THEN VALUE END) AS WIND_SPEED_KPH,
    MAX(CASE WHEN VARIABLE = 'wind_gust' THEN VALUE END) AS WIND_GUST_KPH,
    MAX(CASE WHEN VARIABLE = 'barometric_pressure' THEN VALUE END) AS PRESSURE_PA,
    MAX(CASE WHEN VARIABLE = 'visibility' THEN VALUE END) AS VISIBILITY_M
FROM ranked
WHERE rn = 1
GROUP BY NWS_WEATHER_STATION_ID;

-- Hourly aggregates per station per variable
-- Target lag: 1 hour
CREATE OR REPLACE DYNAMIC TABLE WEATHER_DOMAIN.CURATED.HOURLY_AGGREGATES
  TARGET_LAG = '1 hour'
  WAREHOUSE = WEATHER_WH
AS
SELECT
    NWS_WEATHER_STATION_ID,
    DATE_TRUNC('hour', TIMESTAMP) AS OBSERVATION_HOUR,
    VARIABLE,
    COUNT(*) AS READING_COUNT,
    AVG(VALUE) AS AVG_VALUE,
    MIN(VALUE) AS MIN_VALUE,
    MAX(VALUE) AS MAX_VALUE
FROM WEATHER_DOMAIN.RAW.WEATHER_OBSERVATIONS
GROUP BY NWS_WEATHER_STATION_ID, DATE_TRUNC('hour', TIMESTAMP), VARIABLE;

-- Daily summaries (derived from hourly to reduce compute)
CREATE OR REPLACE DYNAMIC TABLE WEATHER_DOMAIN.CURATED.DAILY_SUMMARIES
  TARGET_LAG = '1 hour'
  WAREHOUSE = WEATHER_WH
AS
SELECT
    NWS_WEATHER_STATION_ID,
    DATE_TRUNC('day', OBSERVATION_HOUR) AS OBSERVATION_DATE,
    VARIABLE,
    SUM(READING_COUNT) AS TOTAL_READINGS,
    AVG(AVG_VALUE) AS DAY_AVG,
    MIN(MIN_VALUE) AS DAY_MIN,
    MAX(MAX_VALUE) AS DAY_MAX
FROM WEATHER_DOMAIN.CURATED.HOURLY_AGGREGATES
GROUP BY NWS_WEATHER_STATION_ID, DATE_TRUNC('day', OBSERVATION_HOUR), VARIABLE;

-- Active weather alerts (enriched with geography)
CREATE OR REPLACE DYNAMIC TABLE WEATHER_DOMAIN.CURATED.ACTIVE_ALERTS
  TARGET_LAG = '15 minutes'
  WAREHOUSE = WEATHER_WH
AS
SELECT
    a.COUNTY_GEO_ID,
    a.NWS_ALERT_ID,
    a.ALERT_STATUS,
    a.EVENT_TYPE,
    a.EVENT_SEVERITY,
    a.EVENT_URGENCY,
    a.ALERT_TITLE,
    a.SENT_TIMESTAMP,
    a.EFFECTIVE_TIMESTAMP,
    a.EXPIRATION_TIMESTAMP,
    g.GEO_NAME AS COUNTY_NAME,
    g.ISO_3166_2_CODE AS STATE_CODE
FROM WEATHER_DOMAIN.RAW.WEATHER_ALERTS a
LEFT JOIN SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.GEOGRAPHY_INDEX g
    ON a.COUNTY_GEO_ID = g.GEO_ID
WHERE a.EXPIRATION_TIMESTAMP >= CURRENT_TIMESTAMP()
  AND a.ALERT_STATUS = 'Actual';
