-- =============================================================
-- Project 02: Real-Time Weather Pipeline
-- Step 03: PRODUCTS Layer (Alerts + Consumption Tables)
-- =============================================================

-- Alert history table (log of triggered threshold breaches)
CREATE OR REPLACE TABLE WEATHER_DOMAIN.PRODUCTS.ALERT_HISTORY (
    ALERT_NAME VARCHAR,
    TRIGGERED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATION_ID VARCHAR,
    METRIC_NAME VARCHAR,
    METRIC_VALUE FLOAT,
    MESSAGE VARCHAR
);

-- Alert 1: Extreme temperature (> 40C or < -30C)
CREATE OR REPLACE ALERT WEATHER_DOMAIN.PRODUCTS.EXTREME_TEMP_ALERT
  WAREHOUSE = WEATHER_WH
  SCHEDULE = '15 MINUTE'
  IF (EXISTS (
    SELECT 1 FROM WEATHER_DOMAIN.CURATED.LATEST_STATION_READINGS
    WHERE TEMPERATURE_C > 40 OR TEMPERATURE_C < -30
  ))
  THEN
    INSERT INTO WEATHER_DOMAIN.PRODUCTS.ALERT_HISTORY
      (ALERT_NAME, STATION_ID, METRIC_NAME, METRIC_VALUE, MESSAGE)
    SELECT
        'EXTREME_TEMP',
        NWS_WEATHER_STATION_ID,
        'temperature_c',
        TEMPERATURE_C,
        'Extreme temperature: ' || TEMPERATURE_C || 'C at ' || NWS_WEATHER_STATION_ID
    FROM WEATHER_DOMAIN.CURATED.LATEST_STATION_READINGS
    WHERE TEMPERATURE_C > 40 OR TEMPERATURE_C < -30;

-- Alert 2: High wind gust (> 100 kph)
CREATE OR REPLACE ALERT WEATHER_DOMAIN.PRODUCTS.HIGH_WIND_ALERT
  WAREHOUSE = WEATHER_WH
  SCHEDULE = '15 MINUTE'
  IF (EXISTS (
    SELECT 1 FROM WEATHER_DOMAIN.CURATED.LATEST_STATION_READINGS
    WHERE WIND_GUST_KPH > 100
  ))
  THEN
    INSERT INTO WEATHER_DOMAIN.PRODUCTS.ALERT_HISTORY
      (ALERT_NAME, STATION_ID, METRIC_NAME, METRIC_VALUE, MESSAGE)
    SELECT
        'HIGH_WIND',
        NWS_WEATHER_STATION_ID,
        'wind_gust_kph',
        WIND_GUST_KPH,
        'High wind gust: ' || WIND_GUST_KPH || ' kph at ' || NWS_WEATHER_STATION_ID
    FROM WEATHER_DOMAIN.CURATED.LATEST_STATION_READINGS
    WHERE WIND_GUST_KPH > 100;

-- Alert 3: Severe NWS alert watcher (Extreme severity)
CREATE OR REPLACE ALERT WEATHER_DOMAIN.PRODUCTS.SEVERE_ALERT_WATCHER
  WAREHOUSE = WEATHER_WH
  SCHEDULE = '15 MINUTE'
  IF (EXISTS (
    SELECT 1 FROM WEATHER_DOMAIN.CURATED.ACTIVE_ALERTS
    WHERE EVENT_SEVERITY = 'Extreme'
  ))
  THEN
    INSERT INTO WEATHER_DOMAIN.PRODUCTS.ALERT_HISTORY
      (ALERT_NAME, STATION_ID, METRIC_NAME, METRIC_VALUE, MESSAGE)
    SELECT
        'SEVERE_NWS_ALERT',
        COUNTY_GEO_ID,
        'event_severity',
        NULL,
        EVENT_TYPE || ' - ' || ALERT_TITLE || ' in ' || COALESCE(COUNTY_NAME, COUNTY_GEO_ID)
    FROM WEATHER_DOMAIN.CURATED.ACTIVE_ALERTS
    WHERE EVENT_SEVERITY = 'Extreme';

-- Resume all alerts
ALTER ALERT WEATHER_DOMAIN.PRODUCTS.EXTREME_TEMP_ALERT RESUME;
ALTER ALERT WEATHER_DOMAIN.PRODUCTS.HIGH_WIND_ALERT RESUME;
ALTER ALERT WEATHER_DOMAIN.PRODUCTS.SEVERE_ALERT_WATCHER RESUME;
