-- Project 07: Earnings Call RAG Pipeline

CREATE DATABASE IF NOT EXISTS EARNINGS_RAG COMMENT = 'Earnings call RAG with Cortex Search and COMPLETE';
CREATE SCHEMA IF NOT EXISTS EARNINGS_RAG.STAGING;
CREATE SCHEMA IF NOT EXISTS EARNINGS_RAG.SEARCH;
CREATE SCHEMA IF NOT EXISTS EARNINGS_RAG.RESULTS;

-- Extract and chunk 5000 transcripts (paragraph-level)
CREATE OR REPLACE TABLE EARNINGS_RAG.STAGING.TRANSCRIPT_CHUNKS AS
WITH source_transcripts AS (
    SELECT COMPANY_ID, PRIMARY_TICKER, COMPANY_NAME, EVENT_TITLE,
        FISCAL_PERIOD, FISCAL_YEAR, EVENT_TIMESTAMP, TRANSCRIPT
    FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.COMPANY_EVENT_TRANSCRIPT_ATTRIBUTES
    WHERE TRANSCRIPT_TYPE = 'SPEAKERS_ANNOTATED' AND EVENT_TYPE = 'Earnings Call'
        AND TRANSCRIPT IS NOT NULL
    LIMIT 5000
),
flattened AS (
    SELECT s.PRIMARY_TICKER, s.COMPANY_NAME, s.EVENT_TITLE, s.FISCAL_PERIOD,
        s.FISCAL_YEAR, s.EVENT_TIMESTAMP, p.INDEX AS PARA_IDX,
        p.VALUE:text::VARCHAR AS PARA_TEXT
    FROM source_transcripts s, LATERAL FLATTEN(input => s.TRANSCRIPT:paragraphs) p
    WHERE p.VALUE:text::VARCHAR IS NOT NULL AND LENGTH(p.VALUE:text::VARCHAR) > 20
)
SELECT MD5(PRIMARY_TICKER || EVENT_TITLE || PARA_IDX::VARCHAR) AS CHUNK_ID,
    PRIMARY_TICKER AS TICKER, COMPANY_NAME, EVENT_TITLE, FISCAL_PERIOD,
    FISCAL_YEAR, EVENT_TIMESTAMP::DATE AS EVENT_DATE, PARA_TEXT AS CHUNK_TEXT
FROM flattened;

-- Create Cortex Search Service
CREATE OR REPLACE CORTEX SEARCH SERVICE EARNINGS_RAG.SEARCH.EARNINGS_SEARCH_SVC
  ON CHUNK_TEXT
  ATTRIBUTES TICKER, COMPANY_NAME, EVENT_TITLE, FISCAL_PERIOD, FISCAL_YEAR
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 hour'
  AS (SELECT CHUNK_ID, TICKER, COMPANY_NAME, EVENT_TITLE, FISCAL_PERIOD, FISCAL_YEAR, EVENT_DATE, CHUNK_TEXT
      FROM EARNINGS_RAG.STAGING.TRANSCRIPT_CHUNKS);

-- Results table for RAG Q&A demos
CREATE OR REPLACE TABLE EARNINGS_RAG.RESULTS.SAMPLE_QA_RESULTS (
    QUESTION VARCHAR, ANSWER VARCHAR,
    SOURCE_TICKER_1 VARCHAR, SOURCE_EVENT_1 VARCHAR,
    SOURCE_TICKER_2 VARCHAR, SOURCE_EVENT_2 VARCHAR,
    SOURCE_CHUNK_PREVIEW VARCHAR
);

-- Example RAG query (run manually for each question):
-- INSERT INTO EARNINGS_RAG.RESULTS.SAMPLE_QA_RESULTS
-- WITH sr AS (
--     SELECT PARSE_JSON(SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
--         'EARNINGS_RAG.SEARCH.EARNINGS_SEARCH_SVC',
--         '{"query":"Your question here","columns":["CHUNK_TEXT","TICKER","EVENT_TITLE"],"limit":3}'
--     )) AS r
-- )
-- SELECT 'question', SNOWFLAKE.CORTEX.COMPLETE('mistral-large2', 'prompt with context'),
--     r:results[0]:TICKER, r:results[0]:EVENT_TITLE,
--     r:results[1]:TICKER, r:results[1]:EVENT_TITLE,
--     LEFT(r:results[0]:CHUNK_TEXT::VARCHAR, 200) FROM sr;
