-- Project 03: Economic Data Vault 2.0
-- Step 03: Business Vault (PIT, Bridges, Consumption Views)

-- PIT: Latest value per indicator-geography pair
CREATE OR REPLACE DYNAMIC TABLE ECON_VAULT.BUSINESS_VAULT.PIT_INDICATOR_LATEST
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT LINK_HK, OBSERVATION_DATE, VALUE, RECORD_SOURCE
FROM ECON_VAULT.RAW_VAULT.SAT_OBSERVATION
QUALIFY ROW_NUMBER() OVER (PARTITION BY LINK_HK ORDER BY OBSERVATION_DATE DESC) = 1;

-- Dashboard view: pre-joined for analyst consumption
CREATE OR REPLACE VIEW ECON_VAULT.BUSINESS_VAULT.VW_ECONOMIC_DASHBOARD AS
SELECT
    hi.VARIABLE AS INDICATOR_CODE,
    sd.VARIABLE_NAME AS INDICATOR_NAME,
    sd.UNIT,
    sd.RECORD_SOURCE AS DATA_SOURCE,
    hg.GEO_ID,
    g.GEO_NAME,
    g.ISO_ALPHA2 AS COUNTRY_CODE,
    s.OBSERVATION_DATE,
    s.VALUE
FROM ECON_VAULT.RAW_VAULT.SAT_OBSERVATION s
JOIN ECON_VAULT.RAW_VAULT.LINK_INDICATOR_GEOGRAPHY l ON s.LINK_HK = l.LINK_HK
JOIN ECON_VAULT.RAW_VAULT.HUB_INDICATOR hi ON l.INDICATOR_HK = hi.INDICATOR_HK
JOIN ECON_VAULT.RAW_VAULT.HUB_GEOGRAPHY hg ON l.GEOGRAPHY_HK = hg.GEOGRAPHY_HK
JOIN ECON_VAULT.RAW_VAULT.SAT_INDICATOR_DETAILS sd ON hi.INDICATOR_HK = sd.INDICATOR_HK
LEFT JOIN SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.GEOGRAPHY_INDEX g ON hg.GEO_ID = g.GEO_ID;

-- Revision tracker: shows how values change across releases
CREATE OR REPLACE VIEW ECON_VAULT.BUSINESS_VAULT.VW_REVISION_TRACKER AS
SELECT
    hi.VARIABLE AS INDICATOR_CODE,
    sd.VARIABLE_NAME AS INDICATOR_NAME,
    hg.GEO_ID,
    v.OBSERVATION_DATE,
    v.RELEASE_DATE,
    v.VALUE,
    v.SOURCE_URL,
    LAG(v.VALUE) OVER (PARTITION BY v.LINK_HK, v.OBSERVATION_DATE ORDER BY v.RELEASE_DATE) AS PREV_VALUE,
    v.VALUE - LAG(v.VALUE) OVER (PARTITION BY v.LINK_HK, v.OBSERVATION_DATE ORDER BY v.RELEASE_DATE) AS REVISION_DELTA
FROM ECON_VAULT.RAW_VAULT.SAT_OBSERVATION_VINTAGE v
JOIN ECON_VAULT.RAW_VAULT.LINK_INDICATOR_GEOGRAPHY l ON v.LINK_HK = l.LINK_HK
JOIN ECON_VAULT.RAW_VAULT.HUB_INDICATOR hi ON l.INDICATOR_HK = hi.INDICATOR_HK
JOIN ECON_VAULT.RAW_VAULT.HUB_GEOGRAPHY hg ON l.GEOGRAPHY_HK = hg.GEOGRAPHY_HK
JOIN ECON_VAULT.RAW_VAULT.SAT_INDICATOR_DETAILS sd ON hi.INDICATOR_HK = sd.INDICATOR_HK;
