-- Project 08: Patent Intelligence (credit-efficient: 50 AI calls)

CREATE DATABASE IF NOT EXISTS PATENT_AI COMMENT = 'Patent intelligence with Cortex AI functions';
CREATE SCHEMA IF NOT EXISTS PATENT_AI.STAGING;
CREATE SCHEMA IF NOT EXISTS PATENT_AI.RESULTS;

-- 2000 recent patents with text
CREATE OR REPLACE TABLE PATENT_AI.STAGING.PATENT_CORPUS AS
SELECT PATENT_ID, INVENTION_TITLE, PATENT_STATUS, PATENT_TYPE, APPLICATION_DATE,
    DOCUMENT_PUBLICATION_DATE, NUMBER_OF_CLAIMS, CPC_SECTION_DESCRIPTION,
    CPC_CLASS_DESCRIPTION, LEFT(PATENT_RAW_TEXT, 2000) AS PATENT_TEXT_TRUNCATED
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.USPTO_PATENT_INDEX
WHERE PATENT_RAW_TEXT IS NOT NULL AND LENGTH(PATENT_RAW_TEXT) > 100
    AND APPLICATION_DATE >= '2023-01-01'
LIMIT 2000;

-- AI classification + summarization (50 patents to save credits)
CREATE OR REPLACE TABLE PATENT_AI.RESULTS.AI_ENRICHED_PATENTS AS
SELECT PATENT_ID, INVENTION_TITLE, APPLICATION_DATE, CPC_SECTION_DESCRIPTION,
    CPC_CLASS_DESCRIPTION, NUMBER_OF_CLAIMS,
    SNOWFLAKE.CORTEX.COMPLETE('mistral-large2',
        'Classify this patent into one category (respond with ONLY the name): AI/ML, Biotech, Clean Energy, Semiconductor, Software, Hardware, Telecom, Chemistry, Mechanical, Other.\nTitle: ' || INVENTION_TITLE || '\nText: ' || LEFT(PATENT_TEXT_TRUNCATED, 500)
    ) AS AI_CATEGORY,
    SNOWFLAKE.CORTEX.COMPLETE('mistral-large2',
        'Summarize in one sentence (max 30 words):\nTitle: ' || INVENTION_TITLE || '\nText: ' || LEFT(PATENT_TEXT_TRUNCATED, 800)
    ) AS AI_SUMMARY
FROM PATENT_AI.STAGING.PATENT_CORPUS LIMIT 50;
