-- Project 05: Healthcare Provider Network Analysis
-- Single-file SQL pipeline (credit-efficient POC)

-- === INFRASTRUCTURE ===
CREATE DATABASE IF NOT EXISTS HEALTH_ML COMMENT = 'Healthcare provider network analysis';
CREATE SCHEMA IF NOT EXISTS HEALTH_ML.STAGING;
CREATE SCHEMA IF NOT EXISTS HEALTH_ML.MODELS;
CREATE SCHEMA IF NOT EXISTS HEALTH_ML.RESULTS;

-- === STAGING: Provider Profiles ===
CREATE OR REPLACE VIEW HEALTH_ML.STAGING.PROVIDER_PROFILES AS
SELECT
    n.NPI, p.GENDER, p.CREDENTIAL, p.IS_SOLE_PROPRIETOR,
    p.NPI_CREATION_DATE, p.NPI_DEACTIVATION_DATE, n.ACTIVE,
    CASE WHEN p.NPI_DEACTIVATION_DATE IS NOT NULL THEN TRUE ELSE FALSE END AS WAS_DEACTIVATED,
    DATEDIFF(year, p.NPI_CREATION_DATE, COALESCE(p.NPI_DEACTIVATION_DATE, CURRENT_DATE())) AS YEARS_ACTIVE,
    t.LEVEL_1_GROUPING AS SPECIALTY_GROUP,
    t.LEVEL_2_CLASSIFICATION AS SPECIALTY_CLASSIFICATION,
    a.STATE, a.GEO_ID_STATE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.NPPES_NPI_INDEX n
JOIN SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.NPPES_PRACTITIONER_ATTRIBUTES p ON n.NPI = p.NPI
LEFT JOIN SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.NPPES_PROVIDER_TAXONOMY_AND_LICENSE_NUMBERS t
    ON n.NPI = t.NPI AND t.IS_PRIMARY_TAXONOMY = TRUE
LEFT JOIN SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.NPPES_PROVIDER_ADDRESSES a
    ON n.NPI = a.NPI AND a.ADDRESS_TYPE = 'Primary Practice'
WHERE a.COUNTRY_CODE = 'US'
LIMIT 5000000;

-- === STAGING: State Density ===
CREATE OR REPLACE VIEW HEALTH_ML.STAGING.STATE_PROVIDER_DENSITY AS
WITH provider_counts AS (
    SELECT STATE, GEO_ID_STATE, SPECIALTY_GROUP,
        COUNT(*) AS PROVIDER_COUNT,
        SUM(CASE WHEN ACTIVE THEN 1 ELSE 0 END) AS ACTIVE_PROVIDERS,
        SUM(CASE WHEN WAS_DEACTIVATED THEN 1 ELSE 0 END) AS DEACTIVATED_COUNT,
        AVG(YEARS_ACTIVE) AS AVG_YEARS_ACTIVE
    FROM HEALTH_ML.STAGING.PROVIDER_PROFILES WHERE STATE IS NOT NULL
    GROUP BY STATE, GEO_ID_STATE, SPECIALTY_GROUP
),
state_pop AS (
    SELECT GEO_ID, VALUE AS POPULATION
    FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.AMERICAN_COMMUNITY_SURVEY_TIMESERIES
    WHERE VARIABLE = 'B01001_001E_5YR' AND GEO_ID LIKE 'geoId/__'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY GEO_ID ORDER BY "DATE" DESC) = 1
)
SELECT pc.*, sp.POPULATION AS STATE_POPULATION,
    ROUND(pc.ACTIVE_PROVIDERS * 100000.0 / NULLIF(sp.POPULATION, 0), 1) AS PROVIDERS_PER_100K
FROM provider_counts pc
LEFT JOIN state_pop sp ON pc.GEO_ID_STATE = sp.GEO_ID;

-- === RESULTS: Provider Clusters ===
CREATE OR REPLACE TABLE HEALTH_ML.RESULTS.PROVIDER_CLUSTERS AS
WITH metrics AS (
    SELECT STATE, SPECIALTY_GROUP, ACTIVE_PROVIDERS, PROVIDERS_PER_100K,
        STATE_POPULATION, AVG_YEARS_ACTIVE,
        NTILE(3) OVER (ORDER BY PROVIDERS_PER_100K) AS DENSITY_TIER,
        NTILE(3) OVER (ORDER BY STATE_POPULATION DESC) AS POP_TIER
    FROM HEALTH_ML.STAGING.STATE_PROVIDER_DENSITY
    WHERE PROVIDERS_PER_100K IS NOT NULL AND SPECIALTY_GROUP IS NOT NULL
)
SELECT *, CASE
    WHEN DENSITY_TIER = 3 AND POP_TIER = 1 THEN 'Metro High-Density'
    WHEN DENSITY_TIER = 1 AND POP_TIER = 3 THEN 'Rural Low-Density'
    WHEN DENSITY_TIER = 3 AND POP_TIER >= 2 THEN 'Academic/Specialty Hub'
    WHEN DENSITY_TIER = 2 THEN 'Suburban Moderate'
    ELSE 'Mixed/Transitional'
END AS CLUSTER_LABEL FROM metrics;

-- === RESULTS: Healthcare Deserts ===
CREATE OR REPLACE TABLE HEALTH_ML.RESULTS.HEALTHCARE_DESERTS AS
WITH medians AS (
    SELECT SPECIALTY_GROUP, MEDIAN(PROVIDERS_PER_100K) AS NATIONAL_MEDIAN_PER_100K
    FROM HEALTH_ML.STAGING.STATE_PROVIDER_DENSITY WHERE PROVIDERS_PER_100K IS NOT NULL
    GROUP BY SPECIALTY_GROUP
)
SELECT d.STATE, d.SPECIALTY_GROUP, d.ACTIVE_PROVIDERS, d.STATE_POPULATION,
    d.PROVIDERS_PER_100K, nm.NATIONAL_MEDIAN_PER_100K,
    ROUND((d.PROVIDERS_PER_100K - nm.NATIONAL_MEDIAN_PER_100K) / NULLIF(nm.NATIONAL_MEDIAN_PER_100K, 0) * 100, 1) AS PCT_BELOW_MEDIAN,
    CASE
        WHEN d.PROVIDERS_PER_100K < nm.NATIONAL_MEDIAN_PER_100K * 0.5 THEN 'Severe Desert'
        WHEN d.PROVIDERS_PER_100K < nm.NATIONAL_MEDIAN_PER_100K * 0.75 THEN 'Moderate Desert'
        WHEN d.PROVIDERS_PER_100K < nm.NATIONAL_MEDIAN_PER_100K THEN 'Mild Shortage'
        ELSE 'Adequate'
    END AS DESERT_CLASSIFICATION
FROM HEALTH_ML.STAGING.STATE_PROVIDER_DENSITY d
JOIN medians nm ON d.SPECIALTY_GROUP = nm.SPECIALTY_GROUP
WHERE d.PROVIDERS_PER_100K IS NOT NULL;

-- === CLASSIFICATION MODEL ===
CREATE OR REPLACE VIEW HEALTH_ML.STAGING.DEACTIVATION_FEATURES AS
SELECT NPI, YEARS_ACTIVE, COALESCE(GENDER,'Unknown') AS GENDER,
    COALESCE(SPECIALTY_GROUP,'Unknown') AS SPECIALTY_GROUP,
    COALESCE(STATE,'Unknown') AS STATE,
    CASE WHEN IS_SOLE_PROPRIETOR THEN 1 ELSE 0 END AS IS_SOLE_PROPRIETOR,
    CASE WHEN CREDENTIAL IS NOT NULL THEN 1 ELSE 0 END AS HAS_CREDENTIAL,
    WAS_DEACTIVATED
FROM HEALTH_ML.STAGING.PROVIDER_PROFILES WHERE YEARS_ACTIVE >= 0;

CREATE OR REPLACE VIEW HEALTH_ML.STAGING.CLASSIFICATION_TRAINING AS
WITH deactivated AS (SELECT YEARS_ACTIVE, GENDER, SPECIALTY_GROUP, STATE, IS_SOLE_PROPRIETOR, HAS_CREDENTIAL, WAS_DEACTIVATED FROM HEALTH_ML.STAGING.DEACTIVATION_FEATURES WHERE WAS_DEACTIVATED = TRUE LIMIT 5000),
active AS (SELECT YEARS_ACTIVE, GENDER, SPECIALTY_GROUP, STATE, IS_SOLE_PROPRIETOR, HAS_CREDENTIAL, WAS_DEACTIVATED FROM HEALTH_ML.STAGING.DEACTIVATION_FEATURES WHERE WAS_DEACTIVATED = FALSE LIMIT 5000)
SELECT * FROM deactivated UNION ALL SELECT * FROM active;

CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION HEALTH_ML.MODELS.DEACTIVATION_CLASSIFIER(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'HEALTH_ML.STAGING.CLASSIFICATION_TRAINING'),
    TARGET_COLNAME => 'WAS_DEACTIVATED'
);
